var SPREADSHEET_ID='1PMnlyYHswnV0nE73Alxh-ocIFtTipB9LMzACdNM9GFs';
var FIELDS={name:3,nickname:4,affiliation:5,role:6,startDate:7,statusWork:8,trainingEnd:9,zone:10,pickType:11,bu:12,shift:13};
var TARGET_KEYS=['overall','fullRack','halfRack','ea','pickToSort','mezzanine','training','fullRackAhAi','fullRackAlBlBmAm','halfRackAjAk','halfRackAnCaBnDa','halfRackBgBh','halfRackBiBk','halfRackCbDbDcCc','halfRackCdCe','halfRackDdDe','halfRackCfDf','microEa','microFa','pickToSortBe'];
function doGet(){return out({ok:true,service:'V3 write',sheets:['2ND','Resigned','V3 Target']});}
function doPost(e){var lock=LockService.getScriptLock();try{lock.waitLock(20000);}catch(x){return out({ok:false,error:'busy'});}try{var b=JSON.parse(e&&e.postData&&e.postData.contents||'{}');if(b.targets)return target(b.targets,b.updatedBy);if(b.rows)return roster(b.rows);return out({ok:false,error:'missing rows or targets'});}catch(x){return out({ok:false,error:String(x.message||x)});}finally{lock.releaseLock();}}
function roster(rows){if(rows.length>200)return out({ok:false,error:'too many rows'});var book=SpreadsheetApp.openById(SPREADSHEET_ID),two=book.getSheetByName('2ND'),res=book.getSheetByName('Resigned');if(!two||!res)return out({ok:false,error:'missing sheet'});var log=[],applied=[],ids=two.getLastRow()>1?two.getRange(2,2,two.getLastRow()-1,1).getDisplayValues():[],resIds=res.getLastRow()>1?res.getRange(2,1,res.getLastRow()-1,1).getDisplayValues():[];rows.forEach(function(e){var id=norm(e.userId),f=e.fields||{};if(!id)return;if(String(e.status||'active')==='resigned'){var r=find(resIds,id);if(!r){r=res.getLastRow()+1;res.getRange(r,1).setValue(String(e.userId).trim());}if(f.name){res.getRange(r,2).setValue(String(f.name).trim());log.push([new Date(),id,'Resigned B',f.name]);}if(f.resignedDate){res.getRange(r,8).setValue(String(f.resignedDate).trim());log.push([new Date(),id,'Resigned H',f.resignedDate]);}applied.push({userId:id,sheet:'Resigned',row:r});return;}var r=find(ids,id);if(!r){r=two.getLastRow()+1;two.getRange(r,2).setValue(String(e.userId).trim());}Object.keys(f).forEach(function(k){if(!FIELDS[k]||!f[k])return;var c=two.getRange(r,FIELDS[k]),old=String(c.getDisplayValue()||'').trim();if(old&&!e.overwrite)return;c.setValue(String(f[k]).trim());log.push([new Date(),id,'2ND '+FIELDS[k],f[k]]);});applied.push({userId:id,sheet:'2ND',row:r});});writeLog(book,log);SpreadsheetApp.flush();return out({ok:true,applied:applied});}
function target(values,who){var book=SpreadsheetApp.openById(SPREADSHEET_ID),s=book.getSheetByName('V3 Target')||book.insertSheet('V3 Target'),old={};if(s.getLastRow()>1)s.getRange(2,1,s.getLastRow()-1,4).getValues().forEach(function(r){old[r[0]]=r[1];});var rows=[['คีย์','ค่า','อัปเดตเมื่อ','โดย']],stamp=new Date();TARGET_KEYS.forEach(function(k){var v=Number(values[k]);if(!isFinite(v)||v<1||v>1000)throw Error('invalid target '+k);rows.push([k,Math.round(v),stamp,who||'V3']);});s.clearContents();s.getRange(1,1,rows.length,4).setValues(rows);writeLog(book,TARGET_KEYS.filter(function(k){return String(old[k])!==String(Math.round(Number(values[k])));}).map(function(k){return [stamp,who||'V3','Target '+k,Math.round(Number(values[k]))];}));return out({ok:true,updatedAt:stamp.toISOString(),updatedBy:who||'V3',targets:values});}
function find(rows,id){for(var i=0;i<rows.length;i++)if(norm(rows[i][0])===id)return i+2;return 0;}
function norm(v){return String(v==null?'':v).replace(/[\s,']/g,'').replace(/\.0+$/,'').toUpperCase();}
function writeLog(book,rows){if(!rows.length)return;var s=book.getSheetByName('V3 Write Log')||book.insertSheet('V3 Write Log');if(s.getLastRow()===0)s.appendRow(['เวลา','รหัส/รายการ','ช่อง','ค่า']);s.getRange(s.getLastRow()+1,1,rows.length,4).setValues(rows.map(function(r){return [r[0],r[1],r[2],r[3]];}));}
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON);}
